/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import java.awt.Image;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author Jefferson
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Imagenes/IconoG.png")).getImage();
        setIconImage(icon);
        jdpPrincipal.setBorder(new ImagenFondo());
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    public static int estacerradoespecialidades(Object obj) {
        JInternalFrame[] activos = jdpPrincipal.getAllFrames();
        int a = 0;
        boolean cerrado = true;
        int i = 0;
        while (i < activos.length && cerrado) {
            if (activos[i] instanceof Gestion_Especialidades) {
//                System.out.println(obj);
//                System.out.println(activos[i].getName());
                a = a + 1;
                cerrado = false;
            }

            i++;
        }

        return a;
    }

    public static int estacerradoverespecialidades(Object obj) {
        JInternalFrame[] activos = jdpPrincipal.getAllFrames();
        int a = 0;
        boolean cerrado = true;
        int i = 0;
        while (i < activos.length && cerrado) {
            if (activos[i] instanceof Ver_Especialidades) {
//                System.out.println(obj);
//                System.out.println(activos[i].getName());
                a = a + 1;
                cerrado = false;
            }

            i++;
        }

        return a;
    }

    public static int estacerradoPacientes(Object obj) {
        JInternalFrame[] activos = jdpPrincipal.getAllFrames();
        int a = 0;
        boolean cerrado = true;
        int i = 0;
        while (i < activos.length && cerrado) {
            if (activos[i] instanceof Gestionar_Pacientes) {
//                System.out.println(obj);
//                System.out.println(activos[i].getName());
                a = a + 1;
                cerrado = false;
            }

            i++;
        }

        return a;
    }

    public static int estacerradoverPacientes(Object obj) {
        JInternalFrame[] activos = jdpPrincipal.getAllFrames();
        int a = 0;
        boolean cerrado = true;
        int i = 0;
        while (i < activos.length && cerrado) {
            if (activos[i] instanceof Ver_Pacientes) {
//                System.out.println(obj);
//                System.out.println(activos[i].getName());
                a = a + 1;
                cerrado = false;
            }

            i++;
        }

        return a;
    }

    public static int estacerradoMedicos(Object obj) {
        JInternalFrame[] activos = jdpPrincipal.getAllFrames();
        int a = 0;
        boolean cerrado = true;
        int i = 0;
        while (i < activos.length && cerrado) {
            if (activos[i] instanceof Gestionar_Medicos) {
//                System.out.println(obj);
//                System.out.println(activos[i].getName());
                a = a + 1;
                cerrado = false;
            }

            i++;
        }

        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEspecialidad = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuPacientes = new javax.swing.JMenu();
        jmiGestionarPacientes = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuMedicos = new javax.swing.JMenu();
        jmiGestionrMedicos = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        MenuHorarios = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        MenuCitas = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        menuExpedientes = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        menuServicios = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        MenuPagos = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        menuUusuarios = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jmiReporteUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                                                                                                                                                                 CITMED CÍTAS MÉDICAS..");

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 0, 0));

        menuEspecialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarEspecialidad.png"))); // NOI18N
        menuEspecialidad.setText("Especialidad");
        menuEspecialidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEspecialidadActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        jMenuItem1.setText("Gestionar Especialidades");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuEspecialidad.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Visulizar.png"))); // NOI18N
        jMenuItem2.setText("Ver Especialidades");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuEspecialidad.add(jMenuItem2);

        jMenuBar1.add(menuEspecialidad);

        menuPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarPaciente.png"))); // NOI18N
        menuPacientes.setText("Pacientes");

        jmiGestionarPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        jmiGestionarPacientes.setText("Gestionar Pacientes");
        jmiGestionarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionarPacientesActionPerformed(evt);
            }
        });
        menuPacientes.add(jmiGestionarPacientes);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Visulizar.png"))); // NOI18N
        jMenuItem4.setText("Ver Pacientes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuPacientes.add(jMenuItem4);

        jMenuBar1.add(menuPacientes);

        menuMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarMedicos.png"))); // NOI18N
        menuMedicos.setText("Medicos");

        jmiGestionrMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        jmiGestionrMedicos.setText("Gestionar Medicos");
        jmiGestionrMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionrMedicosActionPerformed(evt);
            }
        });
        menuMedicos.add(jmiGestionrMedicos);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Visulizar.png"))); // NOI18N
        jMenuItem6.setText("Ver Medicos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuMedicos.add(jMenuItem6);

        jMenuBar1.add(menuMedicos);

        MenuHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Horarios.png"))); // NOI18N
        MenuHorarios.setText("Horarios");

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Visulizar.png"))); // NOI18N
        jMenuItem8.setText("Visualizar Horarios");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        MenuHorarios.add(jMenuItem8);

        jMenuBar1.add(MenuHorarios);

        MenuCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Citas.png"))); // NOI18N
        MenuCitas.setText("Citas");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        jMenuItem9.setText("Gestionar Citas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        MenuCitas.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Visulizar.png"))); // NOI18N
        jMenuItem10.setText("Visualizar Citas");
        MenuCitas.add(jMenuItem10);

        jMenuBar1.add(MenuCitas);

        menuExpedientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Expedientes.png"))); // NOI18N
        menuExpedientes.setText("Expedientes");

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        jMenuItem11.setText("Gestionar Expedientes");
        menuExpedientes.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Visulizar.png"))); // NOI18N
        jMenuItem12.setText("Vizualizar Expedientes");
        menuExpedientes.add(jMenuItem12);

        jMenuBar1.add(menuExpedientes);

        menuServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Servicios.png"))); // NOI18N
        menuServicios.setText("Servicios");

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        jMenuItem13.setText("Gestionar Servicios");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        menuServicios.add(jMenuItem13);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Visulizar.png"))); // NOI18N
        jMenuItem14.setText("Vizualiazar Servicios");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        menuServicios.add(jMenuItem14);

        jMenuBar1.add(menuServicios);

        MenuPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pagos.png"))); // NOI18N
        MenuPagos.setText("Pagos");

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        jMenuItem16.setText("Gestionar Facturas");
        MenuPagos.add(jMenuItem16);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Visulizar.png"))); // NOI18N
        jMenuItem17.setText("Vizualizar Factura");
        MenuPagos.add(jMenuItem17);

        jMenuBar1.add(MenuPagos);

        menuUusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuarios.png"))); // NOI18N
        menuUusuarios.setText("Usuarios");

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        jMenuItem18.setText("Gestionar Usuarios");
        menuUusuarios.add(jMenuItem18);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Visulizar.png"))); // NOI18N
        jMenuItem19.setText("Visualizar Usuarios");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        menuUusuarios.add(jMenuItem19);

        jMenuBar1.add(menuUusuarios);

        menuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reportes.png"))); // NOI18N
        menuReportes.setText("Reportes");

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarPaciente.png"))); // NOI18N
        jMenuItem20.setText("Pacientes Generales");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        menuReportes.add(jMenuItem20);

        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarPaciente.png"))); // NOI18N
        jMenuItem25.setText("Pacientes por Cédula");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        menuReportes.add(jMenuItem25);

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarMedicos.png"))); // NOI18N
        jMenuItem21.setText("Médicos Generales");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        menuReportes.add(jMenuItem21);

        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarMedicos.png"))); // NOI18N
        jMenuItem26.setText("Médicos por Cédula");
        menuReportes.add(jMenuItem26);

        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Expedientes.png"))); // NOI18N
        jMenuItem22.setText("Expedientes");
        menuReportes.add(jMenuItem22);

        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Servicios.png"))); // NOI18N
        jMenuItem23.setText("Servicios");
        menuReportes.add(jMenuItem23);

        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pagos.png"))); // NOI18N
        jMenuItem24.setText("Pagos");
        menuReportes.add(jMenuItem24);

        jmiReporteUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuarios.png"))); // NOI18N
        jmiReporteUsuarios.setText("Usuarios");
        menuReportes.add(jmiReporteUsuarios);

        jMenuBar1.add(menuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Ver_Pacientes verpac = null;
        if (estacerradoverPacientes(verpac) <= 0) {
            verpac = new Ver_Pacientes();
            jdpPrincipal.add(verpac);
            Dimension desktopSize = jdpPrincipal.getSize();
            Dimension FrameSize = verpac.getSize();
            verpac.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            verpac.show();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
AgregarServicio s=new AgregarServicio();
jdpPrincipal.add(s);
s.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem19ActionPerformed


    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Ver_Horario_Medicos verHorario = new Ver_Horario_Medicos();
        jdpPrincipal.add(verHorario);
        Dimension desktopSize = jdpPrincipal.getSize();
        Dimension FrameSize = verHorario.getSize();
        verHorario.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        verHorario.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
Clases_Reportes c = new Clases_Reportes();
c.imprimirReporte("C:\\Users\\micha\\OneDrive\\Documentos\\NetBeansProjects\\ingenieria1\\src\\Reportes\\PacientesGeneral", jdpPrincipal);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void menuEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEspecialidadActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Gestion_Especialidades esp = null;
        if (estacerradoespecialidades(esp) <= 0) {
            esp = new Gestion_Especialidades();
            jdpPrincipal.add(esp);
            Dimension desktopSize = jdpPrincipal.getSize();
            Dimension FrameSize = esp.getSize();
            esp.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            esp.show();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Ver_Especialidades veresp = null;
        if (estacerradoverespecialidades(veresp) <= 0) {
            veresp = new Ver_Especialidades();
            jdpPrincipal.add(veresp);
            Dimension desktopSize = jdpPrincipal.getSize();
            Dimension FrameSize = veresp.getSize();
            veresp.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            veresp.show();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmiGestionarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionarPacientesActionPerformed
        // TODO add your handling code here:
        Gestionar_Pacientes pac = null;
        if (estacerradoPacientes(pac) <= 0) {
            pac = new Gestionar_Pacientes();
            jdpPrincipal.add(pac);
            Dimension desktopSize = jdpPrincipal.getSize();
            Dimension FrameSize = pac.getSize();
            pac.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            pac.show();
        }
    }//GEN-LAST:event_jmiGestionarPacientesActionPerformed

    private void jmiGestionrMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionrMedicosActionPerformed
        // TODO add your handling code here:
        Gestionar_Medicos med = null;
        if (estacerradoMedicos(med) <= 0) {
            med = new Gestionar_Medicos();
            jdpPrincipal.add(med);
            Dimension desktopSize = jdpPrincipal.getSize();
            Dimension FrameSize = med.getSize();
            med.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            med.show();
        }
    }//GEN-LAST:event_jmiGestionrMedicosActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        Ver_Medicos vermed = null;
        if (estacerradoMedicos(vermed) <= 0) {
            vermed = new Ver_Medicos();
            jdpPrincipal.add(vermed);
            Dimension desktopSize = jdpPrincipal.getSize();
            Dimension FrameSize = vermed.getSize();
            vermed.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vermed.show();
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        Agregar_Cita hormed = new Agregar_Cita();
        jdpPrincipal.add(hormed);
        Dimension desktopSize = jdpPrincipal.getSize();
        Dimension FrameSize = hormed.getSize();
        hormed.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        hormed.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
VerServicio v=new VerServicio();
jdpPrincipal.add(v);
v.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
Clases_Reportes c = new Clases_Reportes();
c.imprimirReporte("C:\\Users\\micha\\OneDrive\\Documentos\\NetBeansProjects\\ingenieria1\\src\\Reportes\\MedicosGenerales", jdpPrincipal);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (InstantiationException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MenuCitas;
    public javax.swing.JMenu MenuHorarios;
    public javax.swing.JMenu MenuPagos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    public static javax.swing.JDesktopPane jdpPrincipal;
    public javax.swing.JMenuItem jmiGestionarPacientes;
    public javax.swing.JMenuItem jmiGestionrMedicos;
    public javax.swing.JMenuItem jmiReporteUsuarios;
    public javax.swing.JMenu menuEspecialidad;
    public javax.swing.JMenu menuExpedientes;
    public javax.swing.JMenu menuMedicos;
    public javax.swing.JMenu menuPacientes;
    public javax.swing.JMenu menuReportes;
    public javax.swing.JMenu menuServicios;
    public javax.swing.JMenu menuUusuarios;
    // End of variables declaration//GEN-END:variables
}
